# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moother' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moother

  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  
end
